version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --lower_case_table_names=1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prisma
    ports:
      - '3306:3306'
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h127.0.0.1', '-P3306' ]
      interval: 5s
      timeout: 2s
      retries: 20
